# Site settings
title: cờ ca ro
motto: cờ ca ro
email: oafarm.vn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  cờ ca ro 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cocaro.github.io" # the base hostname & protocol for your site
twitter_username: mth2610
github_username:  mth2610

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
